### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by Qwerrty574** [ErrrOrrr503/waydroid-server-manual#1]
> Allow` **inoming** connections from host to the desired port and replies from this port to the host.

**Comment by Qwerrty574** [comment]
> \# **disablig** nft to use iptables

**Comment by ErrrOrrr503** [comment]
Fixed in https://github.com/ErrrOrrr503/waydroid-server-manual/commit/28421eb344ae24d28aae5422dda90f043d8d2ea2
